# Generated by Django 5.0 on 2024-06-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='point',
            field=models.IntegerField(default=1),
        ),
    ]
