# Generated by Django 5.0 on 2024-11-26 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationimage',
            name='challenge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='challenge.challenge'),
            preserve_default=False,
        ),
    ]
