# Generated by Django 5.0 on 2024-11-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_confirmationimage_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='questions_json',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
