# Generated by Django 5.0 on 2024-05-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_remove_question_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
