# Generated by Django 5.0 on 2024-08-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_alter_profile_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='answered_at',
            field=models.DateTimeField(),
        ),
    ]
