# Generated by Django 5.0 on 2024-12-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0005_useranswer_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationimage',
            name='image',
            field=models.FileField(upload_to='confirmation/'),
        ),
    ]
