# Generated by Django 5.0 on 2024-08-23 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0005_alter_useranswer_answered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='is_empty',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='challenge.answer'),
        ),
    ]
