# Generated by Django 5.0 on 2024-12-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0006_alter_confirmationimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmationimage',
            name='image',
            field=models.ImageField(upload_to='confirmation/'),
        ),
    ]
