# Generated by Django 5.0 on 2024-08-24 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0006_useranswer_is_empty_alter_useranswer_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='challenge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='challenge.challenge'),
            preserve_default=False,
        ),
    ]
