# Generated by Django 5.0 on 2024-11-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0007_useranswer_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='questions_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
