# Generated by Django 5.0 on 2024-06-12 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0010_complexity'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='complexity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='challenge.complexity'),
            preserve_default=False,
        ),
    ]
